//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApopeiStefan_CSI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApopeiStefan_CSI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18,19,20,36,55,62,76,87.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48,97.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23,44,92.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05,29,66.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00,06,13,32,52,53,71,72,83,93,94.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24,45.
        /// </summary>
        public static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01,96.
        /// </summary>
        public static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17,28,63,74,89.
        /// </summary>
        public static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03,10,34,35,54,56,77,86.
        /// </summary>
        public static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95.
        /// </summary>
        public static string J {
            get {
                return ResourceManager.GetString("J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 67.
        /// </summary>
        public static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04,08,27,64.
        /// </summary>
        public static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33,51,80.
        /// </summary>
        public static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02,37,38,59,61,69,70.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11,15,25,41,42,57,78,85.
        /// </summary>
        public static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12,50.
        /// </summary>
        public static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        public static string Q {
            get {
                return ResourceManager.GetString("Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09,26,39,60,75,88.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (AY)(BR)(CU)(DH)(EQ)(FS)(GL)(IP)(JX)(KN)(MO)(TZ)(VW).
        /// </summary>
        public static string ReflectorB {
            get {
                return ResourceManager.GetString("ReflectorB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (AF)(BV)(CP)(DJ)(EI)(GO)(HY)(KR)(LZ)(MX)(NW)(TQ)(SU).
        /// </summary>
        public static string ReflectorC {
            get {
                return ResourceManager.GetString("ReflectorC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKMFLGDQVZNTOWYHXUSPAIBRCJ.
        /// </summary>
        public static string Rotor1 {
            get {
                return ResourceManager.GetString("Rotor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTZPSFBOKMWRCJDIVLAEYUXHGQ.
        /// </summary>
        public static string Rotor10 {
            get {
                return ResourceManager.GetString("Rotor10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AJDKSIRUXBLHWTMCQGZNPYFVOE.
        /// </summary>
        public static string Rotor2 {
            get {
                return ResourceManager.GetString("Rotor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDFHJLCPRTXVZNYEIWGAKMUSQO.
        /// </summary>
        public static string Rotor3 {
            get {
                return ResourceManager.GetString("Rotor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESOVPZJAYQUIRHXLNFTGKDCMWB.
        /// </summary>
        public static string Rotor4 {
            get {
                return ResourceManager.GetString("Rotor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VZBRGITYUPSDNHLXAWMJQOFECK.
        /// </summary>
        public static string Rotor5 {
            get {
                return ResourceManager.GetString("Rotor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPGVOUMFYQBENHZRDKASXLICTW.
        /// </summary>
        public static string Rotor6 {
            get {
                return ResourceManager.GetString("Rotor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZJHGRCXMYSWBOUFAIVLPEKQDT.
        /// </summary>
        public static string Rotor7 {
            get {
                return ResourceManager.GetString("Rotor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FKQHTLXOCBJSPDZRAMEWNIUYGV.
        /// </summary>
        public static string Rotor8 {
            get {
                return ResourceManager.GetString("Rotor8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JGDQOXUSCAMIFRVTPNEWKBLZYH.
        /// </summary>
        public static string Rotor9 {
            get {
                return ResourceManager.GetString("Rotor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,16,30,31,43,58,73,79,84.
        /// </summary>
        public static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07,22,91.
        /// </summary>
        public static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81,98.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49,68.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46.
        /// </summary>
        public static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
